public class Interfone(abstract) {
    String nome;
    String numero;
    String modelo;
    String endereco;

    public void ligarPara(String nome,String numero){
        this.nome = nome;
        this.numero = numero;
    }
    
    public void registrarChamada(String nome,String horario, String duracao){
        
    }

}

public class InterfoneResidencial(Interfone){
    public void cadastrarContato(String nome,String numero):

    public void ligarPara(String nome,String numero):

    public void registrarChamada(String nome,String horario, String duracao):
}