nome = input('qual o seu nome? ')
print(f'bem vindo senhor(a) {nome}, agilizamos sua compra')
valornaconta = int(input('informe o valor que disponivel na conta: '))
valordevenda = int(input('coloque o valor da compra do imóvel: '))
print (f'o valor total da compra foi de {valornaconta - valordevenda} deseja continuar?')